# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api_options.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'api_options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61pi_options.proto\x12\rnorthstar.web\x1a google/protobuf/descriptor.proto:5\n\x0bhttp_method\x12\x1e.google.protobuf.MethodOptions\x18\xb9\x8e\x03 \x01(\t:3\n\thttp_path\x12\x1e.google.protobuf.MethodOptions\x18\xba\x8e\x03 \x01(\t::\n\x10runtime_required\x12\x1e.google.protobuf.MethodOptions\x18\xbb\x8e\x03 \x01(\x08:7\n\x0erequired_field\x12\x1d.google.protobuf.FieldOptions\x18\xc3\x8e\x03 \x01(\x08:1\n\x08nullable\x12\x1d.google.protobuf.FieldOptions\x18\xc4\x8e\x03 \x01(\x08:7\n\x0e\x61llowed_values\x12\x1d.google.protobuf.FieldOptions\x18\xc5\x8e\x03 \x01(\t::\n\x11string_or_integer\x12\x1d.google.protobuf.FieldOptions\x18\xc6\x8e\x03 \x01(\x08:5\n\nroot_array\x12\x1f.google.protobuf.MessageOptions\x18\xcd\x8e\x03 \x01(\x08:3\n\x08\x65vidence\x12\x1f.google.protobuf.MessageOptions\x18\xce\x8e\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'northstar_quant.web.api_options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
# @@protoc_insertion_point(module_scope)
