# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\rnorthstar.web\"\x07\n\x05\x45mpty\"\xdd\x01\n\x05\x45rror\x12\x13\n\x06\x64\x65tail\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06status\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x17\n\nrequest_id\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x17\n\nruntime_id\x18\x04 \x01(\tH\x03\x88\x01\x01\x12\x10\n\x03url\x18\x05 \x01(\tH\x04\x88\x01\x01\x12\x19\n\x0crejection_id\x18\x06 \x01(\tH\x05\x88\x01\x01\x42\t\n\x07_detailB\t\n\x07_statusB\r\n\x0b_request_idB\r\n\x0b_runtime_idB\x06\n\x04_urlB\x0f\n\r_rejection_idb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'northstar_quant.web.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=31
  _globals['_EMPTY']._serialized_end=38
  _globals['_ERROR']._serialized_start=41
  _globals['_ERROR']._serialized_end=262
# @@protoc_insertion_point(module_scope)
