"""严格 PIT 因子定义、暴露、分析与 research-only 组合提案。"""

from northstar_quant.research.factors.analysis import analyze_factor
from northstar_quant.research.factors.engine import FactorCheckpointComputation, FactorEngine
from northstar_quant.research.factors.models import (
    FactorAnalysisPeriod,
    FactorAnalysisResult,
    FactorCheckpointData,
    FactorDefinition,
    FactorExposure,
    FactorForwardOutcome,
    FactorMarketSlice,
    FactorMaterializationReference,
    FactorPipelineConfig,
    FactorPortfolioProposal,
    FactorPortfolioWeight,
    FactorResearchError,
    FactorResearchExperiment,
    FactorResearchRunManifest,
    FactorRobustnessCostScenario,
    FactorRobustnessCostScenarioResult,
    FactorRobustnessFactorSummary,
    FactorRobustnessParameterVariant,
    FactorRobustnessParameterVariantResult,
    FactorRobustnessPlan,
    FactorRobustnessResult,
    FactorRobustnessScenarioResult,
    FactorRole,
    FactorStabilityThresholds,
    FactorRobustnessSubperiod,
    FactorWalkForwardResult,
    ProposalStatus,
)
from northstar_quant.research.factors.portfolio import build_factor_portfolio_proposal
from northstar_quant.research.factors.robustness import (
    FactorRobustnessEvaluator,
    FactorRobustnessParameterVariantEvidence,
)

__all__ = [
    "FactorAnalysisPeriod",
    "FactorAnalysisResult",
    "FactorCheckpointComputation",
    "FactorCheckpointData",
    "FactorDefinition",
    "FactorEngine",
    "FactorExposure",
    "FactorForwardOutcome",
    "FactorMarketSlice",
    "FactorMaterializationReference",
    "FactorPipelineConfig",
    "FactorPortfolioProposal",
    "FactorPortfolioWeight",
    "FactorResearchError",
    "FactorResearchExperiment",
    "FactorResearchRunManifest",
    "FactorRobustnessCostScenario",
    "FactorRobustnessCostScenarioResult",
    "FactorRobustnessEvaluator",
    "FactorRobustnessFactorSummary",
    "FactorRobustnessParameterVariant",
    "FactorRobustnessParameterVariantEvidence",
    "FactorRobustnessParameterVariantResult",
    "FactorRobustnessPlan",
    "FactorRobustnessResult",
    "FactorRobustnessScenarioResult",
    "FactorRole",
    "FactorStabilityThresholds",
    "FactorRobustnessSubperiod",
    "FactorWalkForwardResult",
    "ProposalStatus",
    "analyze_factor",
    "build_factor_portfolio_proposal",
]
