worker_processes 1;
error_log /dev/stderr warn;
pid /tmp/nginx.pid;
events { worker_connections 128; }
http {
    access_log off;
    client_body_temp_path /tmp/client;
    proxy_temp_path /tmp/proxy;
    fastcgi_temp_path /tmp/fastcgi;
    uwsgi_temp_path /tmp/uwsgi;
    scgi_temp_path /tmp/scgi;
    resolver 127.0.0.11 valid=5s;
    server {
        listen 8080;
        client_max_body_size 1k;
        location ~ "^/api/publications(/[0-9a-f-]{36})?$" {
            limit_except GET { deny all; }
            set $api http://data-api:19082;
            proxy_pass $api$request_uri;
            proxy_connect_timeout 3s;
            proxy_read_timeout 15s;
            proxy_set_header Authorization $http_authorization;
        }
        location / { return 404; }
    }
}
