"""Documented publisher identities, not codes inferred from futures products.

Tushare doc_id=468, reviewed 2026-09-15. This is the published discovery list,
not an assertion of exhaustive historical index coverage or data availability.
"""

REFERENCE = "https://tushare.pro/document/2?doc_id=468"
INDEX_NAMES = {
    "NHAI.NH": "南华农产品指数",
    "NHCI.NH": "南华商品指数",
    "NHECI.NH": "南华能化指数",
    "NHFI.NH": "南华黑色指数",
    "NHII.NH": "南华工业品指数",
    "NHMI.NH": "南华金属指数",
    "NHNFI.NH": "南华有色金属",
    "NHPMI.NH": "南华贵金属指数",
    "A.NH": "南华连大豆指数",
    "AG.NH": "南华沪银指数",
    "AL.NH": "南华沪铝指数",
    "AP.NH": "南华郑苹果指数",
    "AU.NH": "南华沪黄金指数",
    "BB.NH": "南华连胶合板指数",
    "BU.NH": "南华沪石油沥青指数",
    "C.NH": "南华连玉米指数",
    "CF.NH": "南华郑棉花指数",
    "CS.NH": "南华连玉米淀粉指数",
    "CU.NH": "南华沪铜指数",
    "CY.NH": "南华棉纱指数",
    "ER.NH": "南华郑籼稻指数",
    "FB.NH": "南华连纤维板指数",
    "FG.NH": "南华郑玻璃指数",
    "FU.NH": "南华沪燃油指数",
    "HC.NH": "南华沪热轧卷板指数",
    "I.NH": "南华连铁矿石指数",
    "J.NH": "南华连焦炭指数",
    "JD.NH": "南华连鸡蛋指数",
    "JM.NH": "南华连焦煤指数",
    "JR.NH": "南华郑粳稻指数",
    "L.NH": "南华连乙烯指数",
    "LR.NH": "南华郑晚籼稻指数",
    "M.NH": "南华连豆粕指数",
    "ME.NH": "南华郑甲醇指数",
    "NI.NH": "南华沪镍指数",
    "P.NH": "南华连棕油指数",
    "PB.NH": "南华沪铅指数",
    "PP.NH": "南华连聚丙烯指数",
    "RB.NH": "南华沪螺钢指数",
    "RM.NH": "南华郑菜籽粕指数",
    "RO.NH": "南华郑菜油指数",
    "RS.NH": "南华郑油菜籽指数",
    "RU.NH": "南华沪天胶指数",
    "SC.NH": "南华原油指数",
    "SF.NH": "南华郑硅铁指数",
    "SM.NH": "南华郑锰硅指数",
    "SN.NH": "南华沪锡指数",
    "SP.NH": "南华纸浆指数",
    "SR.NH": "南华郑白糖指数",
    "TA.NH": "南华郑精对苯二甲酸指数",
    "TC.NH": "南华郑动力煤指数",
    "V.NH": "南华连聚氯乙烯指数",
    "WR.NH": "南华沪线材指数",
    "WS.NH": "南华郑强麦指数",
    "Y.NH": "南华连豆油指数",
    "ZN.NH": "南华沪锌指数",
}
