#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

# No xtrace may observe entered credentials, even when invoked with bash -x.
set +x
umask 077
TOTAL_STAGES=2
SIMNOW_REPO=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
SIMNOW_PRIVATE_DIR="$SIMNOW_REPO/.northstar"
if [[ -L "$SIMNOW_PRIVATE_DIR" ]]; then
  printf 'Refusing a symbolic-link private directory.\n' >&2
  exit 1
fi
mkdir -p "$SIMNOW_PRIVATE_DIR"
ENV_FILE="$SIMNOW_PRIVATE_DIR/simnow.env"
if [[ -L "$ENV_FILE" || ( -e "$ENV_FILE" && ( ! -f "$ENV_FILE" || ! -O "$ENV_FILE" ) ) ]]; then
  printf 'Credentials must be your own regular file, not a symbolic link.\n' >&2
  exit 1
fi
if [[ -f "$ENV_FILE" ]]; then chmod 600 "$ENV_FILE"; fi
if [[ ! -t 0 ]]; then
  printf 'Run this wizard interactively in your own terminal.\n' >&2
  exit 1
fi

banner "SimNow · 本机私密配置"
stage "确认仿真账号与客户端认证"
say "只写本机私密文件，不写 GitHub、不登录柜台、不报单或撤单。"
open_url "https://www.simnow.com.cn/"
step "登录你已注册的 SimNow 官网，在个人中心确认投资者代码；不是昵称。"
ask NORTHSTAR_SIMNOW_USER_ID "投资者代码："
if [[ ! "$NORTHSTAR_SIMNOW_USER_ID" =~ ^[0-9]{1,12}$ ]]; then
  warn "投资者代码必须为 1–12 位数字。"
  exit 1
fi
open_url "https://www.simnow.com.cn/product.action"
step "对照官方环境说明和该账号当前设置，确认 AppID 与 AuthCode。"
note "官网说明中的公共测试默认值是 simnow_client_test / 16 个 0；这里由你明确填写，不代替认证验收。"
ask NORTHSTAR_SIMNOW_APP_ID "AppID："
ask_secret NORTHSTAR_SIMNOW_AUTH_CODE "AuthCode（隐藏输入）："
if [[ -z "$NORTHSTAR_SIMNOW_APP_ID" || -z "$NORTHSTAR_SIMNOW_AUTH_CODE" ]]; then
  warn "AppID 和 AuthCode 不能为空。"
  exit 1
fi

stage "保存交易登录密码"
say "请输入可用于 CTP 仿真交易登录的密码，不要发到聊天或工单。"
ask_secret NORTHSTAR_SIMNOW_PASSWORD "交易密码（隐藏输入）："
if [[ -z "$NORTHSTAR_SIMNOW_PASSWORD" ]]; then
  warn "密码不能为空。"
  exit 1
fi
if ! confirm "将以上配置保存到本机私密文件？已有同名配置将更新，不连接柜台"; then
  exit 0
fi
write_env NORTHSTAR_SIMNOW_USER_ID "$NORTHSTAR_SIMNOW_USER_ID"
write_env NORTHSTAR_SIMNOW_APP_ID "$NORTHSTAR_SIMNOW_APP_ID"
write_env NORTHSTAR_SIMNOW_AUTH_CODE "$NORTHSTAR_SIMNOW_AUTH_CODE"
write_env NORTHSTAR_SIMNOW_PASSWORD "$NORTHSTAR_SIMNOW_PASSWORD"
chmod 600 "$ENV_FILE"
unset NORTHSTAR_SIMNOW_PASSWORD NORTHSTAR_SIMNOW_AUTH_CODE
finish
say "这是逐行字面量配置，不要 source 或执行此文件。"
say "本机 Python 入口需要设置配置文件路径（不是密码）："
printf '  export NORTHSTAR_SIMNOW_CONFIG=%q\n' "$ENV_FILE"
say "Docker 接入使用 compose.simnow.yaml 的只读私密文件挂载。"
say "配置完成不等于已登录、已核对或允许生产交易。"
